services:
    Plenta\ContaoTestimonialsBundle\EventListener\DataContainer\PaletteManipulatorCallback:
        public: true
        arguments:
            - '@request_stack'

    plenta.testimonials.listener.data_container:
        class: Plenta\ContaoTestimonialsBundle\EventListener\DataContainer\DataContainerListener
        public: true
        autowire: true
        autoconfigure: true
